controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_position_controller:
      type: effort_controllers/JointPositionController
      ros__parameters:
        joints:
          - joint1
          - joint2
        
        command_interfaces:
          - position
        
        state_interfaces:
          - position
          - velocity
          - effort
        
        gains:
          joint1:
            p: 100.0
            i: 0.01
            d: 5.0
          joint2:
            p: 80.0
            i: 0.01
            d: 4.0

        constraints:
          stopped_velocity_tolerance: 0.01
          goal_time: 0.0
          max_velocity:
            joint1: 2.0
            joint2: 2.0 