controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
      joints:
        - joint1
        - joint2

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position 